# -*- coding: utf-8 -*-
"""iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1irOzi1A_rWRA0MpQtFKkMLsU5bCxMYke
"""

from sklearn import datasets

data = datasets.load_iris()
X = data.data

import numpy as np

class PCA:

  def __init__(self, n_components):
    self.n_components = n_components
    self.n_components = None
    self.mean = None

  def fit(self, X):
    self.mean = np.mean(X, axis=0)
    X = X - self.mean

    cov = np.cov(X.T)
    eigenvalues, eigenvectors = np.linalg.eig(cov)

    eigenvectors = eigenvectors.T
    idxs = np.argsort(eigenvalues)[::-1]

    eigenvalues = eigenvalues[idxs]
    eigenvectors = eigenvectors[idxs]

    self.components = eigenvectors[0:self.n_components]

  def transform(self, X):
    X = X - self.mean
    return np.dot(X, self.components.T)

pca = PCA(2)
pca.fit(X)
X_projected = pca.transform(X)
X_projected[:2]

